### ISSUE TITLE
Allow all factory functions to be `async`?

### ISSUE THREAD

**Issue by dotansimha** [contrawork/graphql-helix#14]
customParse, customValidate and so on. 

Also related: 
https://github.com/contrawork/graphql-helix/pull/12

**Comment by n1ru4l** [comment]
I don't wanna force this on graphql-helix, but instead of having a separate factory function for every single thing, it could be possible to just do one that covers all use-cases? E.g. like I am doing that in my Socket.io transport: https://github.com/n1ru4l/graphql-live-query/blob/9acc7c7714462fbd4bfbf28fb2902056be4a5fa5/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L47-L79

**Comment by dotansimha** [comment]
> I don't wanna force this on graphql-helix, but instead of having a separate factory function for every single thing, it could be possible to just do one that covers all use-cases? E.g. like I am doing that in my Socket.io transport: [n1ru4l/graphql-live-query@`9acc7c7`/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L47-L79](https://github.com/n1ru4l/graphql-live-query/blob/9acc7c7714462fbd4bfbf28fb2902056be4a5fa5/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L47-L79)

Yeah, that totally makes sense, but it has an additional side-effect because then graphql-helix is no longer in control of the execution flow (parsing -> validation -> execution) and it needs to be implemented separately, right?

**Comment by n1ru4l** [comment]
I don't think so that this would disrupt the flow. If you take a quick look here the function is just used to get all the dependencies for executing the operation: https://github.com/n1ru4l/graphql-live-query/blob/9acc7c7714462fbd4bfbf28fb2902056be4a5fa5/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L212-L234


So the example API for graphql-helix could look like this:

```ts
const result = await processRequest(async () => ({
  operationName,
  query,
  variables,
  request,
  schema,
}));
```

But at the same time, the factory function could also be called in userland before passing stuff to processRequest?

```ts
const params = await (async () => ({
  operationName,
  query,
  variables,
  request,
  schema,
}))()
const result = await processRequest(params);
```

**Comment by dotansimha** [comment]
> I don't think so that this would disrupt the flow. If you take a quick look here the function is just used to get all the dependencies for executing the operation: [n1ru4l/graphql-live-query@`9acc7c7`/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L212-L234](https://github.com/n1ru4l/graphql-live-query/blob/9acc7c7714462fbd4bfbf28fb2902056be4a5fa5/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L212-L234) Maybe that approach indeed makes more sense for more transport restrictive implementations 🤔
> 
> So the example API for graphql-helix could look like this:
> 
> ```ts
> const result = await processRequest(async () => ({
>   operationName,
>   query,
>   variables,
>   request,
>   schema,
> }));
> ```
> 
> But at the same time, the factory function could also be called in userland before passing stuff to processRequest?
> 
> ```ts
> const params = await (async () => ({
>   operationName,
>   query,
>   variables,
>   request,
>   schema,
> }))()
> const result = await processRequest(params);
> ```

Oh ok I see now :) It does makes a lot of sense :)

**Comment by danielrearden** [comment]
Closing. As discussed, this can be done outside of `processRequest`.
