### ISSUE TITLE
Future for this repository

### ISSUE THREAD

**Issue by ajotaos** [contrawork/graphql-helix#27]
Is there a future planned for this repo?

I think this library it's amazing because of its modularity and some projects at my workplace are considering using `graphql-helix` on top of Fastify. Even though what already exists is great, I noticed there's been no commits or work done for a little over a month so I'm considering the long term journey of this repo for the decision.

Is there a roadmap, future plans, maintenance plans for this repo or is it meant to be archived soon?

Thanks

**Comment by danielrearden** [comment]
Hi @ajotaos. Thanks for inquiring 😄  We will definitely continue to maintain this repo for the foreseeable future. Because GraphQL Helix is dependency-free and feature-complete, there will not be frequent updates to the repo. For the same reason, there's not much in terms of a roadmap. The biggest change we have planned is splitting off `renderGraphiQL` into its own package (I will actually be tackling that this coming week). As `graphql-js` continues to evolve, we will update GraphQL Helix as needed to support all bleeding-edge features. However, most server-specific features fall outside the scope of this project and are more suitable as [envelop](https://github.com/dotansimha/envelop) plugins instead.
