### ISSUE TITLE
Export parseQuery function

### ISSUE THREAD

**Issue by n1ru4l** [contrawork/graphql-helix#29]
I think for custom use-cases it makes sense to expose the parseQuery function to the user in order to have a consistent error handling.

**Comment by danielrearden** [comment]
@n1ru4l I'm hesitant to expose this as a configuration option simply because one of the few things Helix is actually _supposed_ to do is abstract away the error handling logic, ensuring it follows the GraphQL over HTTP spec (although the spec is currently fairly vague around error handling so we are currently following the conventions established by `express-graphql`).

Can you provide more context around what it is about the current API that prevents consistent error handling?

**Comment by n1ru4l** [comment]
I need to parse the document before processRequest, as I need to apply some extra logic depending on the parsed document and would like to use the exact same error handling as if I passed the operation string instead of the operation AST to processRequest.

**Comment by danielrearden** [comment]
Would it be reasonable to just use a custom `parse` function in that case? `parse` can not be asynchronous if that helps.

**Comment by n1ru4l** [comment]
No, since I pick the schema based on the parsed document 😅
